AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy EC2, RDS (MySQL), and Lambda

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: tartela

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group
      SubnetIds:
        - subnet-02985573b62ab9966  # us-east-1a
        - subnet-0563cd0982dbf76a6  # us-east-1b
      Tags:
        - Key: Name
          Value: MyDBSubnetGroup

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.41
      MasterUsername: admin
      MasterUserPassword: password123456
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
      - sg-024946b702581d6e5

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: ami-000d41719f4ab3d23
      SubnetId: subnet-02985573b62ab9966
      SecurityGroupIds:
      - sg-024946b702581d6e5

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          echo "<h1>Hello from EC2</h1>" > /var/www/html/index.html

  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloLambda
      Handler: index.handler
      Role: arn:aws:iam::941377145211:role/service-role/ScheduledLambda-role-97hhej34
      Runtime: python3.9
      Code:
        ZipFile: |
          def handler(event, context):
              print("Hello from Lambda")
              return { "statusCode": 200, "body": "Hello from Lambda" }
